import type { Application, Retreat } from "./supabase/types";

export const MOCK_RETREAT: Retreat = {
  id: "retreat-001",
  slug: "amazonia-2026",
  name: "Amazonía · Retiro de silencio",
  description:
    "Un encuentro íntimo de cinco días en el corazón de la selva amazónica. Un espacio para escuchar, para soltar, para recordar quiénes somos cuando el ruido cesa.",
  location: "Colombia",
  start_date: "2026-09-10",
  end_date: "2026-09-15",
  total_spots: 12,
  price_cents: 220000,
  currency: "USD",
  is_open: true,
  created_at: "2026-05-01T00:00:00Z",
};

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "app-001",
    retreat_id: "retreat-001",
    name: "Valentina Moreno",
    email: "valentina@ejemplo.com",
    country: "Colombia",
    profession: "Diseñadora gráfica",
    why_attend:
      "Llevo dos años buscando un espacio de silencio real. Trabajo en diseño y siento que necesito reconectar con algo más profundo que la pantalla. He leído sobre ÚNA y siento que este retiro es lo que he estado esperando.",
    how_heard: "instagram",
    social_media: "@vale.moreno",
    phone: null,
    q_draw: null,
    q_work_intersection: null,
    q_responsible_participation: null,
    org_connection: null,
    travel_availability: null,
    investment_comfort: null,
    num_attendees: 1,
    status: "pending",
    access_code: null,
    access_code_expires_at: null,
    access_code_email_sent: false,
    notes: null,
    created_at: "2026-06-20T14:32:00Z",
    updated_at: "2026-06-20T14:32:00Z",
    retreat: MOCK_RETREAT,
  },
  {
    id: "app-002",
    retreat_id: "retreat-001",
    name: "Camila Restrepo",
    email: "camila@ejemplo.com",
    country: "México",
    profession: "Psicóloga",
    why_attend:
      "Trabajo con personas en procesos de duelo y transformación. Quiero vivir en primera persona lo que proponen estos espacios para poder acompañar mejor desde mi práctica.",
    how_heard: "referido",
    social_media: "",
    phone: null,
    q_draw: null,
    q_work_intersection: null,
    q_responsible_participation: null,
    org_connection: null,
    travel_availability: null,
    investment_comfort: null,
    num_attendees: 2,
    status: "approved",
    access_code: "MZKT-8R4N",
    access_code_expires_at: "2026-07-02T00:00:00Z",
    access_code_email_sent: true,
    notes: null,
    created_at: "2026-06-18T09:15:00Z",
    updated_at: "2026-06-22T11:00:00Z",
    retreat: MOCK_RETREAT,
  },
  {
    id: "app-003",
    retreat_id: "retreat-001",
    name: "Laura Jiménez",
    email: "laura@ejemplo.com",
    country: "España",
    profession: "Escritora",
    why_attend:
      "Estoy terminando mi segunda novela y siento que necesito un espacio de quietud antes de entregarla. La selva siempre ha sido un lugar de revelación para mí.",
    how_heard: "boca-a-boca",
    social_media: "@laurajimenez.escribe",
    phone: null,
    q_draw: null,
    q_work_intersection: null,
    q_responsible_participation: null,
    org_connection: null,
    travel_availability: null,
    investment_comfort: null,
    num_attendees: 1,
    status: "pending",
    access_code: null,
    access_code_expires_at: null,
    access_code_email_sent: false,
    notes: null,
    created_at: "2026-06-21T18:45:00Z",
    updated_at: "2026-06-21T18:45:00Z",
    retreat: MOCK_RETREAT,
  },
  {
    id: "app-004",
    retreat_id: "retreat-001",
    name: "Sofía Hernández",
    email: "sofia@ejemplo.com",
    country: "Argentina",
    profession: "Médica",
    why_attend:
      "Quiero aprender a estar presente. La medicina me ha enseñado mucho sobre el cuerpo, pero poco sobre el silencio.",
    how_heard: "evento",
    social_media: "",
    phone: null,
    q_draw: null,
    q_work_intersection: null,
    q_responsible_participation: null,
    org_connection: null,
    travel_availability: null,
    investment_comfort: null,
    num_attendees: 1,
    status: "rejected",
    access_code: null,
    access_code_expires_at: null,
    access_code_email_sent: false,
    notes: null,
    created_at: "2026-06-15T11:20:00Z",
    updated_at: "2026-06-19T09:30:00Z",
    retreat: MOCK_RETREAT,
  },
];
